//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFileSystemFileWatcher.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class ExchangeEntities : DbContext
    {
        public ExchangeEntities()
            : base("name=ExchangeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int procCheckDBForUpdate()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("procCheckDBForUpdate");
        }
    
        public virtual int procCreateSHPCONMessages()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("procCreateSHPCONMessages");
        }
    
        public virtual int procCreateWHSCONMessage()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("procCreateWHSCONMessage");
        }
    
        public virtual int procCreateWMMBXYMessages(Nullable<int> tpChangeID)
        {
            var tpChangeIDParameter = tpChangeID.HasValue ?
                new ObjectParameter("tpChangeID", tpChangeID) :
                new ObjectParameter("tpChangeID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("procCreateWMMBXYMessages", tpChangeIDParameter);
        }
    
        public virtual int procCreateWMMBXYMessages_120(Nullable<int> tpChangeID)
        {
            var tpChangeIDParameter = tpChangeID.HasValue ?
                new ObjectParameter("tpChangeID", tpChangeID) :
                new ObjectParameter("tpChangeID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("procCreateWMMBXYMessages_120", tpChangeIDParameter);
        }
    
        public virtual int procCreateWMMBXYMessages_2_CONS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("procCreateWMMBXYMessages_2_CONS");
        }
    
        public virtual int procCreateWMMBXYOnlyEMailMessages(Nullable<int> tpChangeID)
        {
            var tpChangeIDParameter = tpChangeID.HasValue ?
                new ObjectParameter("tpChangeID", tpChangeID) :
                new ObjectParameter("tpChangeID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("procCreateWMMBXYOnlyEMailMessages", tpChangeIDParameter);
        }
    
        public virtual ObjectResult<string> procCreateZWM_STK_BALMessages()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("procCreateZWM_STK_BALMessages");
        }
    
        public virtual int procGetIncomingMessages(string filename, string msg_txt)
        {
            var filenameParameter = filename != null ?
                new ObjectParameter("filename", filename) :
                new ObjectParameter("filename", typeof(string));
    
            var msg_txtParameter = msg_txt != null ?
                new ObjectParameter("msg_txt", msg_txt) :
                new ObjectParameter("msg_txt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("procGetIncomingMessages", filenameParameter, msg_txtParameter);
        }
    
        public virtual ObjectResult<procGetOutgoingEMails_Result> procGetOutgoingEMails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<procGetOutgoingEMails_Result>("procGetOutgoingEMails");
        }
    
        public virtual ObjectResult<procGetOutgoingMessages_Result> procGetOutgoingMessages()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<procGetOutgoingMessages_Result>("procGetOutgoingMessages");
        }
    
        public virtual int procUpdateFromBATMAS(Nullable<int> incomingMessageID)
        {
            var incomingMessageIDParameter = incomingMessageID.HasValue ?
                new ObjectParameter("IncomingMessageID", incomingMessageID) :
                new ObjectParameter("IncomingMessageID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("procUpdateFromBATMAS", incomingMessageIDParameter);
        }
    
        public virtual int procUpdateFromDESADV(Nullable<int> incomingMessageID)
        {
            var incomingMessageIDParameter = incomingMessageID.HasValue ?
                new ObjectParameter("IncomingMessageID", incomingMessageID) :
                new ObjectParameter("IncomingMessageID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("procUpdateFromDESADV", incomingMessageIDParameter);
        }
    
        public virtual int procUpdateFromMATMAS(Nullable<int> incomingMessageID)
        {
            var incomingMessageIDParameter = incomingMessageID.HasValue ?
                new ObjectParameter("IncomingMessageID", incomingMessageID) :
                new ObjectParameter("IncomingMessageID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("procUpdateFromMATMAS", incomingMessageIDParameter);
        }
    
        public virtual int procUpdateFromSHPORD(Nullable<int> incomingMessageID)
        {
            var incomingMessageIDParameter = incomingMessageID.HasValue ?
                new ObjectParameter("IncomingMessageID", incomingMessageID) :
                new ObjectParameter("IncomingMessageID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("procUpdateFromSHPORD", incomingMessageIDParameter);
        }
    
        public virtual int procUpdateOutgoingMessagesResult(Nullable<int> messageID, Nullable<int> statusOut, string result)
        {
            var messageIDParameter = messageID.HasValue ?
                new ObjectParameter("MessageID", messageID) :
                new ObjectParameter("MessageID", typeof(int));
    
            var statusOutParameter = statusOut.HasValue ?
                new ObjectParameter("StatusOut", statusOut) :
                new ObjectParameter("StatusOut", typeof(int));
    
            var resultParameter = result != null ?
                new ObjectParameter("Result", result) :
                new ObjectParameter("Result", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("procUpdateOutgoingMessagesResult", messageIDParameter, statusOutParameter, resultParameter);
        }
    
        public virtual int procGetInboxMessage_test(string fileName, string fileBody)
        {
            var fileNameParameter = fileName != null ?
                new ObjectParameter("fileName", fileName) :
                new ObjectParameter("fileName", typeof(string));
    
            var fileBodyParameter = fileBody != null ?
                new ObjectParameter("fileBody", fileBody) :
                new ObjectParameter("fileBody", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("procGetInboxMessage_test", fileNameParameter, fileBodyParameter);
        }
    
        public virtual ObjectResult<procGetOutboxMessage_test_Result> procGetOutboxMessage_test()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<procGetOutboxMessage_test_Result>("procGetOutboxMessage_test");
        }
    }
}
